language: elixir

sudo: false

elixir:
  - 1.1.1
  - 1.2.5

otp_release:
  - 18.0
  - 18.3

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7

env:
  - CC=clang-3.7 CXX=clang++-3.7 ARCHFLAGS=-Wgcc-compat

after_script:
  - "rm -rf _build deps ebin"
  - "make tests"
